name: "Deploy To AWS S3"
description: "Deploy a static website via AWS S3"
inputs:
  bucket-name:
    description: "The name of the S3 bucket"
    required: true
  bucket-region:
    description: "The AWS region of the S3 bucket"
    required: false
    default: "us-east-1"
  source-dir:
    description: "The directory to deploy"
    required: true
outputs:
  website-url:
    description: "The URL of the deployed website"
runs:
  using: "node20"
  main: "main.js"
